//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenShop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TokenShop.fa", typeof(fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        internal static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        internal static string account_number {
            get {
                return ResourceManager.GetString("account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل پیوست.
        /// </summary>
        internal static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجه.
        /// </summary>
        internal static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی حساب.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک.
        /// </summary>
        internal static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب/کارتهای بانکی.
        /// </summary>
        internal static string bank_accounts {
            get {
                return ResourceManager.GetString("bank_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیش های بانکی.
        /// </summary>
        internal static string bank_receiptions {
            get {
                return ResourceManager.GetString("bank_receiptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت.
        /// </summary>
        internal static string cart_number {
            get {
                return ResourceManager.GetString("cart_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        internal static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2018 کلیه حقوق برای dgbt محفوظ هست.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبرد.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاهش.
        /// </summary>
        internal static string decrease {
            get {
                return ResourceManager.GetString("decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ واریز.
        /// </summary>
        internal static string deposit_date {
            get {
                return ResourceManager.GetString("deposit_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تایید.
        /// </summary>
        internal static string draft {
            get {
                return ResourceManager.GetString("draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول.
        /// </summary>
        internal static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزایش.
        /// </summary>
        internal static string increase {
            get {
                return ResourceManager.GetString("increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعتبر.
        /// </summary>
        internal static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی.
        /// </summary>
        internal static string national_code {
            get {
                return ResourceManager.GetString("national_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت آیتم جدید.
        /// </summary>
        internal static string new_record {
            get {
                return ResourceManager.GetString("new_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست جدید.
        /// </summary>
        internal static string new_request {
            get {
                return ResourceManager.GetString("new_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحله بعد.
        /// </summary>
        internal static string next_step {
            get {
                return ResourceManager.GetString("next_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه ای یافت نشد.
        /// </summary>
        internal static string no_found {
            get {
                return ResourceManager.GetString("no_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکتهای باز.
        /// </summary>
        internal static string open_tickets {
            get {
                return ResourceManager.GetString("open_tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه پرداخت.
        /// </summary>
        internal static string pay_mode {
            get {
                return ResourceManager.GetString("pay_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت.
        /// </summary>
        internal static string periority {
            get {
                return ResourceManager.GetString("periority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشت وجه.
        /// </summary>
        internal static string pick_price {
            get {
                return ResourceManager.GetString("pick_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مقدار این فیلد را وارد نمایید.
        /// </summary>
        internal static string please_fill_field {
            get {
                return ResourceManager.GetString("please_fill_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری من.
        /// </summary>
        internal static string profile_me {
            get {
                return ResourceManager.GetString("profile_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای عدم تغییر در کلمه عبور این فیلد را خالی بگذارید.
        /// </summary>
        internal static string release_empty {
            get {
                return ResourceManager.GetString("release_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور خود را فراموش کرده اید؟.
        /// </summary>
        internal static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        internal static string repassword {
            get {
                return ResourceManager.GetString("repassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ درخواست.
        /// </summary>
        internal static string request_date {
            get {
                return ResourceManager.GetString("request_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت.
        /// </summary>
        internal static string resean {
            get {
                return ResourceManager.GetString("resean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عودت وجه.
        /// </summary>
        internal static string return_price {
            get {
                return ResourceManager.GetString("return_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ردیف در هر صفحه.
        /// </summary>
        internal static string row_per_page {
            get {
                return ResourceManager.GetString("row_per_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پاسخ به این پیام.
        /// </summary>
        internal static string send_replay {
            get {
                return ResourceManager.GetString("send_replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        internal static string sheba {
            get {
                return ResourceManager.GetString("sheba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبریک.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال درخواست پشتیبانی.
        /// </summary>
        internal static string ticket_send {
            get {
                return ResourceManager.GetString("ticket_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام های پشتیبانی.
        /// </summary>
        internal static string tickets {
            get {
                return ResourceManager.GetString("tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید توکن.
        /// </summary>
        internal static string token_buy {
            get {
                return ResourceManager.GetString("token_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست خرید توکن.
        /// </summary>
        internal static string token_buy_request {
            get {
                return ResourceManager.GetString("token_buy_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما با موفقیت ثبت گردید، بعد از تایید اطلاعات فیش واریزی توکنهای درخواستی به حساب شما منظور خواهد شد.
        /// </summary>
        internal static string token_buy_request_success {
            get {
                return ResourceManager.GetString("token_buy_request_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد توکن.
        /// </summary>
        internal static string token_count {
            get {
                return ResourceManager.GetString("token_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گردش حساب توکن ها.
        /// </summary>
        internal static string token_transactions {
            get {
                return ResourceManager.GetString("token_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال توکن.
        /// </summary>
        internal static string token_transfer {
            get {
                return ResourceManager.GetString("token_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه گیرنده توکن.
        /// </summary>
        internal static string token_transfer_reciption_id {
            get {
                return ResourceManager.GetString("token_transfer_reciption_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گیرنده توکن.
        /// </summary>
        internal static string token_transfer_reciption_name {
            get {
                return ResourceManager.GetString("token_transfer_reciption_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست انتقال توکن شما با موفقیت انجام شد.
        /// </summary>
        internal static string token_transfer_success {
            get {
                return ResourceManager.GetString("token_transfer_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال.
        /// </summary>
        internal static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملکرد.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فوری.
        /// </summary>
        internal static string urgent {
            get {
                return ResourceManager.GetString("urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده.
        /// </summary>
        internal static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبسایت.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
